### ISSUE TITLE
make buttons functionable

### ISSUE THREAD

**Issue by om1621** [opencodeiiita/interactive-map#11]
on moving mouse on button the original image should be replaced by corresponding correct image e.g if you mouseover on  village button , image with village area as shaded portion should replace original image and when you remove mouse original image should re-appear

**Comment by blaze-assault** [comment]
Claim

**Comment by sggts04** [comment]
claim

**Comment by ananya-mohanty** [comment]
Claim

**Comment by om1621** [comment]
@blaze-assault go on :)

**Comment by cyber-venom003** [comment]
claim

**Comment by garvitchittora** [comment]
claim

**Comment by blaze-assault** [comment]
sir i have 1 day more for completing the task .i will do it by then .

**Comment by cyber-venom003** [comment]
@om1621 Sir, if deadline exceeds then please assign it to me!!!

**Comment by prince-7** [comment]
claim

**Comment by blaze-assault** [comment]
Sir i was busy with some other issues as i thought i have time for this one .. Sir i will do  it by tomorrow  .if i am unable to do it  then you assign it to anyone else .
@om1621

**Comment by om1621** [comment]
do this by 12 (i.e you have 3 hours) , otherwise i have to assign this to someone else.

**Comment by blaze-assault** [comment]
@om1621   sir assign it to someone else.

**Comment by sarthakm21** [comment]
Claim

**Comment by sggts04** [comment]
can I work in it? I claimed it 2nd after blaze-assault

**Comment by om1621** [comment]
@sggts04  go on .

**Comment by om1621** [comment]
Provide a live link

**Comment by sggts04** [comment]
https://shreyasgupta.in/interactive-map/
