### ISSUE TITLE
make the app responsive

### ISSUE THREAD

**Issue by om1621** [opencodeiiita/interactive-map#15]
i.e size of image and buttons should vary according to screen width (e.g in mobile view image size is very large , give image a proper size)

**Comment by sggts04** [comment]
claim

**Comment by cyber-venom003** [comment]
__CLAIM__

**Comment by sggts04** [comment]
nevermind, @cyber-venom003 can have this :)

**Comment by om1621** [comment]
@cyber-venom003 go on :)

**Comment by cyber-venom003** [comment]
Thank you @om1621 @sggts04
