### ISSUE TITLE
give the error message on the screen in place of alert box.

### ISSUE THREAD

**Issue by om1621** [opencodeiiita/interactive-map#17]
i.e only option for search is through search bar

**Comment by blaze-assault** [comment]
Claim

**Comment by om1621** [comment]
@blaze-assault go on

**Comment by pradhuman1** [comment]
claim

**Comment by blaze-assault** [comment]
@om1621 sir please clarify the isssue that where do i have to show error message and on what basis.
if search is empty then??

**Comment by om1621** [comment]
show the error message below the search button and error is caused when input does not matches village , office  and other names on buttons (also when input is empty).

**Comment by blaze-assault** [comment]
https://blaze-assault.github.io/interactive-map/index.html

here is live link .coorected isssue no. 17   made a pr
