### ISSUE TITLE
change font family of text to Cera pro

### ISSUE THREAD

**Issue by om1621** [opencodeiiita/interactive-map#3]
font files are present in the fonts foder

**Comment by sarthakm21** [comment]
can i work on this??

**Comment by om1621** [comment]
Comment on github not on mail and if any one have not assigned for this
then u can

**Comment by om1621** [comment]
yes

**Comment by Mukul-M** [comment]
can i work on this issue

**Comment by om1621** [comment]
it is already assigned dude :)
