### ISSUE TITLE
change the background with a beautiful gradient 

### ISSUE THREAD

**Issue by om1621** [opencodeiiita/interactive-map#4]
you can change font colors according to your gradient color

**Comment by cyber-venom003** [comment]
I wanna work on this!!!

**Comment by Codedude1** [comment]
Is this issue currently open? I wanna work on it.

**Comment by om1621** [comment]
ok

**Comment by Mukul-M** [comment]
can i work on this issue

**Comment by om1621** [comment]
it is already assigned :)
